In [30]:
import pandas as pd
import numpy as np
import datetime

vendas_df = pd.read_csv("vendas_tech.csv", low_memory=False)
gerentes_df = pd.read_excel("gerentes_lojas.xlsx" )

display(vendas_df)
print("-"*200)
display(gerentes_df)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

In [31]:
#Inspeção
display(vendas_df.head())
print("-"*200)
display(vendas_df.tail())
print("-"*200)
display(vendas_df.sample())
print("-"*200)
display(vendas_df.shape)
print("-"*200)
display(vendas_df.info())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
29420,29421,2024-03-14,Curitiba,Teclado Mecânico,250.0,1,Cliente_9032,NaN

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

(100100, 8)

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  str
 2   Loja            98099 non-null   str
 3   Produto         100100 non-null  str
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  str
 7   Data_Base       1 non-null       str
dtypes: float64(1), int64(2), str(5)
memory usage: 6.1 MB

None

In [32]:
#Tratamento de dados

#colunas
vendas_analise = vendas_df.drop(columns=["Data_Base"])


#nulos
#vendas_analise = vendas_analise.dropna() -> exclui todas as linhas que tem um valor vazio
vendas_analise["Loja"] = vendas_analise["Loja"].fillna("Online")

#tipo de dados
vendas_analise["Data"] = pd.to_datetime(vendas_analise["Data"], format="%Y-%m-%d")

#padronização
vendas_analise["Loja"] = vendas_analise["Loja"].str.strip()
vendas_analise["Loja"] = vendas_analise["Loja"].str.title()

gerentes_df["Loja"] = gerentes_df["Loja"].str.strip()
gerentes_df["Loja"] = gerentes_df["Loja"].str.title()

#Duplicatas
vendas_analise = vendas_analise.drop_duplicates(subset=["ID_Pedido"])
display(vendas_analise)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237

In [33]:
#Novas colunas

#Faturamento
vendas_analise["Faturamento"] = vendas_analise["Preco_Unitario"] * vendas_analise["Qtd"]

#Região
display(vendas_analise["Loja"].unique())
dict_regiao = {
    'São Paulo' : 'Sudeste',
    'Belo Horizonte' : 'Sudeste',
    'Online' : 'Online',
    'Rio De Janeiro' : 'Sudeste',
    'Salvador' : 'Nordeste',
    'Recife' : 'Nordeste',
    'Curitiba' : 'Sul',
    'Porto Alegre' : 'Sul'

}

vendas_analise["Região"] = vendas_analise["Loja"].map(dict_regiao)
#Forma de venda
vendas_analise["Forma_de_venda"] = np.where(vendas_analise["Loja"] == "Online", "Online", "Presencial")
display(vendas_analise)

<StringArray>
[     'São Paulo', 'Belo Horizonte',         'Online', 'Rio De Janeiro',
       'Salvador',         'Recife',       'Curitiba',   'Porto Alegre']
Length: 8, dtype: str

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Região,Forma_de_venda
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Sudeste,Presencial
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Sudeste,Presencial
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Sudeste,Presencial
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Sudeste,Presencial
...,...,...,...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,240.0,Sudeste,Presencial
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058,40.0,Sudeste,Presencial
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864,4400.0,Sul,Presencial
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205,5500.0,Sul,Presencial
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237,250.0,Sul,Presencial

In [34]:
#Analizar

vendas_analise = vendas_analise.sort_values(by=["Data"], ascending=False)
vendas_analise = vendas_analise.reset_index(drop=True)
#display(vendas_analise)
#.loc -> por nome da coluna e nome da linha
loja = vendas_analise.loc[3, "Loja"]
produto = vendas_analise.loc[3, "Produto"]
cliente = vendas_analise.loc[3, "Cliente"]
print(loja, produto, cliente)
#.iloc -> por posição
#condicao

#df_id_4 = vendas_analise[vendas_analise["ID_Pedido"] == 4]
#display(df_id_4)
#Exportar pedaços da base

df_vendas_sp = vendas_analise[vendas_analise["Loja"] == "São Paulo"]
df_vendas_sp.to_csv("Vendas_Sao_Paulo.csv",index=False, sep=";")

#exportar as vendas de 2024
df_vendas_2024 = vendas_analise[vendas_analise["Data"].dt.year == 2024]



df_hdmi_sul = vendas_analise[(vendas_analise["Produto"] == "Cabo HDMI") & (vendas_analise["Região"] == "Sul")]

# & == E
# | == OU

display(df_hdmi_sul)

Porto Alegre Teclado Mecânico Cliente_22452

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Região,Forma_de_venda
59,78584,2024-12-30,Curitiba,Cabo HDMI,40.0,1,Cliente_21307,40.0,Sul,Presencial
63,75695,2024-12-30,Porto Alegre,Cabo HDMI,40.0,1,Cliente_29587,40.0,Sul,Presencial
74,47774,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_14363,80.0,Sul,Presencial
104,35127,2024-12-30,Curitiba,Cabo HDMI,40.0,2,Cliente_20687,80.0,Sul,Presencial
127,64473,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_11598,80.0,Sul,Presencial
...,...,...,...,...,...,...,...,...,...,...
99914,49140,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_24445,40.0,Sul,Presencial
99928,70138,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_9348,40.0,Sul,Presencial
99945,97659,2023-01-01,Curitiba,Cabo HDMI,40.0,1,Cliente_58,40.0,Sul,Presencial
99974,37130,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_22886,40.0,Sul,Presencial
99999,42051,2023-01-01,Curitiba,Cabo HDMI,40.0,10,Cliente_16622,400.0,Sul,Presencial

In [35]:
rank_vendas = vendas_analise[["Loja", "Faturamento"]].groupby("Loja").sum(numeric_only=True)
rank_vendas = rank_vendas.sort_values(by="Faturamento", ascending=False)
rank_vendas = rank_vendas.reset_index()
rank_vendas["Faturamento"] = rank_vendas["Faturamento"].map("R${:,.2f}".format)
display(rank_vendas)
print()

             Loja      Faturamento
0        Salvador  R$42,300,610.00
1  Rio De Janeiro  R$42,294,720.00
2          Recife  R$42,190,390.00
3       São Paulo  R$42,090,690.00
4  Belo Horizonte  R$41,714,890.00
5    Porto Alegre  R$41,678,460.00
6        Curitiba  R$41,121,720.00
7          Online   R$6,080,850.00

In [36]:
#mais venderam no Online
df_vendas_online = vendas_analise[vendas_analise["Loja"] == "Online"]
rank_vendas_online = df_vendas_online[["Produto", "Faturamento"]].groupby("Produto").sum(numeric_only=True)
rank_vendas_online = rank_vendas_online.sort_values(by="Faturamento", ascending=False)
rank_vendas_online = rank_vendas_online.reset_index()
rank_vendas_online["Faturamento"] = rank_vendas_online["Faturamento"].map("R${:,.2f}".format)
display(rank_vendas_online)

              Produto     Faturamento
0           iPhone 14  R$2,145,000.00
1         Notebook HP  R$1,414,400.00
2       Notebook Dell  R$1,291,500.00
3  Smartphone Samsung    R$684,200.00
4         Monitor 27"    R$398,400.00
5    Teclado Mecânico     R$85,750.00
6         Mouse Gamer     R$45,480.00
7           Cabo HDMI     R$16,120.00

In [37]:
#Analize de rank por loja e produto

analise_produtos_em_lojas = vendas_analise[["Loja", "Produto", "Qtd"]].groupby(["Loja", "Produto"]).sum()
analise_lojas_em_prdutos = vendas_analise[["Loja", "Produto", "Qtd"]].groupby(["Produto", "Loja"]).sum()
display(analise_produtos_em_lojas)
display(analise_lojas_em_prdutos)

                                    Qtd
Loja           Produto
Belo Horizonte Cabo HDMI           2636
               Monitor 27"         2625
               Mouse Gamer         2465
               Notebook Dell       2654
               Notebook HP         2775
...                                 ...
São Paulo      Notebook Dell       2535
               Notebook HP         2592
               Smartphone Samsung  2476
               Teclado Mecânico    2589
               iPhone 14           2735

[64 rows x 1 columns]

                           Qtd
Produto   Loja
Cabo HDMI Belo Horizonte  2636
          Curitiba        2698
          Online           403
          Porto Alegre    2571
          Recife          2534
...                        ...
iPhone 14 Porto Alegre    2540
          Recife          2652
          Rio De Janeiro  2702
          Salvador        2671
          São Paulo       2735

[64 rows x 1 columns]

In [41]:
#Quais gerentes bateram a meta Jan 2023?
df_vendas_gerentes = vendas_analise[(vendas_analise["Data"].dt.year==2023) & (vendas_analise["Data"].dt.month == 1)]

df_vendas_gerentes = df_vendas_gerentes[["Loja", "Faturamento"]].groupby("Loja", as_index=False).sum(numeric_only=True)
df_vendas_gerentes = df_vendas_gerentes.merge(gerentes_df,on="Loja", how="left")
df_vendas_gerentes["Bateu_Meta"] = np.where(df_vendas_gerentes["Faturamento"] >= df_vendas_gerentes["Meta_Mensal"], "Sim","Não")
display(df_vendas_gerentes)

             Loja  Faturamento   Gerente  Meta_Mensal Bateu_Meta
0  Belo Horizonte    1779100.0   Juliana      55000.0        Sim
1        Curitiba    1986920.0   Roberto      45000.0        Sim
2          Online     404570.0       NaN          NaN        Não
3    Porto Alegre    1726640.0     Pedro      42000.0        Sim
4          Recife    1779020.0    Marcos      48000.0        Sim
5  Rio De Janeiro    1736830.0  Fernanda      60000.0        Sim
6        Salvador    1686070.0       Ana      52000.0        Sim
7       São Paulo    1831140.0    Carlos      50000.0        Sim